### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by caesaragen** [xitoring/xitogent#1]
![xi](https://user-images.githubusercontent.com/11316233/150306097-ea89453b-768d-453f-951e-1e48723e1775.png)

Hi, I am experiencing the above error during installation.

**Comment by mbrodala** [comment]
![image](https://user-images.githubusercontent.com/5037116/165509490-00a55d5f-db34-4ac5-93b7-755a92cb1ac2.png)

**Comment by Xitoring-Team** [comment]
Hello,

Xitogent v1 is out of support, please use Xitogent v2. the installation command can be found on your Xitoring control panel.

If you have any concerns, please don't hesitate to contact us at support @ xitoring.com
